import { useState } from "react"
import {
  Activity,
  AlertTriangle,
  CalendarDays,
  CheckCircle2,
  ClipboardCheck,
  FileArchive,
  FileBarChart,
  FileCheck2,
  FileClock,
  History,
  LockKeyhole,
  SearchCheck,
  Shield,
  ShieldAlert,
  UserRoundCheck,
  Workflow,
} from "lucide-react"
import DataTable from "../components/ui/DataTable"
import FilterBar, { SelectFilter } from "../components/ui/FilterBar"
import KpiCard from "../components/ui/KpiCard"
import PageHeader from "../components/ui/PageHeader"
import StatusBadge from "../components/ui/StatusBadge"
import type { Page } from "../types"

interface FilterOption {
  label: string
  value: string
}

interface AuditPageProps {
  currentPage?: Page
}

interface AuditFilterValues {
  module: string
  result: string
  severity: string
}

interface AuditPageDetail {
  title: string
  subtitle: string
}

const PERIOD_OPTIONS: FilterOption[] = [
  { label: "Today", value: "today" },
  { label: "Yesterday", value: "yesterday" },
  { label: "Last 7 Days", value: "7-days" },
  { label: "Last 30 Days", value: "30-days" },
]

const MODULE_OPTIONS: FilterOption[] = [
  { label: "Assets", value: "assets" },
  { label: "Inventory", value: "inventory" },
  { label: "Service Requests", value: "service-requests" },
  { label: "Work Orders", value: "work-orders" },
]

const RESULT_OPTIONS: FilterOption[] = [
  { label: "Success", value: "success" },
  { label: "Failed", value: "failed" },
]

const SEVERITY_OPTIONS: FilterOption[] = [
  { label: "Information", value: "information" },
  { label: "Warning", value: "warning" },
  { label: "Critical", value: "critical" },
]

const EMPTY_FILTER_OPTIONS: FilterOption[] = []
const EMPTY_DATA: Record<string, string | number>[] = []

const AUDIT_COLUMNS = [
  { key: "timestamp", label: "Timestamp", sortable: true },
  { key: "actor", label: "Actor" },
  { key: "role", label: "Role" },
  { key: "action", label: "Action" },
  { key: "module", label: "Module" },
  { key: "entity", label: "Entity" },
  { key: "entityId", label: "Entity ID" },
  { key: "result", label: "Result" },
  { key: "severity", label: "Severity" },
  { key: "details", label: "Details" },
]

const CLOSURE_COLUMNS = [
  { key: "record", label: "Record" },
  { key: "module", label: "Module" },
  { key: "submittedBy", label: "Submitted By" },
  { key: "approver", label: "Approver" },
  { key: "previousState", label: "Previous State" },
  { key: "approvedState", label: "Approved State" },
  { key: "approvalDate", label: "Approval Date", sortable: true },
  { key: "status", label: "Status" },
  { key: "evidence", label: "Evidence" },
]

const CHANGE_COLUMNS = [
  { key: "timestamp", label: "Timestamp", sortable: true },
  { key: "actor", label: "Actor" },
  { key: "module", label: "Module" },
  { key: "entity", label: "Entity" },
  { key: "field", label: "Field" },
  { key: "previousValue", label: "Previous Value" },
  { key: "updatedValue", label: "Updated Value" },
  { key: "reason", label: "Reason" },
]

const WORKFLOW_COLUMNS = [
  { key: "timestamp", label: "Timestamp", sortable: true },
  { key: "actor", label: "Actor" },
  { key: "previousState", label: "Previous State" },
  { key: "newState", label: "New State" },
  { key: "reason", label: "Reason" },
  { key: "evidence", label: "Evidence" },
]

const EVIDENCE_COLUMNS = [
  { key: "recordId", label: "Record ID" },
  { key: "module", label: "Module" },
  { key: "entity", label: "Entity" },
  { key: "evidenceType", label: "Evidence Type" },
  { key: "recordedBy", label: "Recorded By" },
  { key: "recordedAt", label: "Recorded At", sortable: true },
  { key: "reference", label: "Reference" },
]

const EXPORT_COLUMNS = [
  { key: "exportId", label: "Export ID" },
  { key: "exportType", label: "Export Type" },
  { key: "createdBy", label: "Created By" },
  { key: "dateRange", label: "Date Range" },
  { key: "filters", label: "Filters" },
  { key: "createdAt", label: "Created At", sortable: true },
  { key: "status", label: "Status" },
  { key: "file", label: "File" },
  { key: "expiry", label: "Expiry" },
]

const REPORT_COLUMNS = [
  { key: "reportType", label: "Report Type" },
  { key: "dateRange", label: "Date Range" },
  { key: "module", label: "Module" },
  { key: "generatedBy", label: "Generated By" },
  { key: "generatedAt", label: "Generated At", sortable: true },
  { key: "status", label: "Status" },
  { key: "actions", label: "Actions" },
]

const REPORT_TYPES = [
  "User / Approval Audit",
  "Workflow Change",
  "Approval History",
  "Closure History",
  "Audit Event",
  "Evidence Register",
]

const PAGE_DETAILS: Partial<Record<Page, AuditPageDetail>> = {
  audit: {
    title: "Audit Dashboard",
    subtitle:
      "Monitor system activity, workflow changes, approvals, closures, evidence and audit history across FieldOps Nexus.",
  },
  "audit-logs": {
    title: "Audit Logs",
    subtitle:
      "Search immutable activity, actor traceability, authentication events and system outcomes.",
  },
  "audit-closures": {
    title: "Closure Approvals",
    subtitle:
      "Review the read-only history of closure decisions already completed in source workflows.",
  },
  "audit-history": {
    title: "Change History",
    subtitle:
      "Trace field changes and workflow state transitions without modifying source records.",
  },
  "audit-evidence": {
    title: "Evidence / Audit Exports",
    subtitle:
      "Review evidence references and generated audit export history when supplied by connected services.",
  },
  "audit-reports": {
    title: "Audit Reports",
    subtitle:
      "Review available compliance report history without generating unsupported production data.",
  },
}

function Section({
  title,
  description,
  children,
}: {
  title: string
  description?: string
  children: React.ReactNode
}) {
  return (
    <div className="space-y-3">
      <div>
        <div className="text-sm font-600 text-text-primary">{title}</div>
        {description && (
          <p className="mt-1 text-xs leading-relaxed text-text-secondary">
            {description}
          </p>
        )}
      </div>
      {children}
    </div>
  )
}

function AvailabilityPanel({
  icon,
  title,
  message,
}: {
  icon: React.ReactNode
  title: string
  message: string
}) {
  return (
    <div className="flex min-h-40 items-center gap-4 rounded-lg border border-border bg-white p-5">
      <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-surface-2 text-text-secondary">
        {icon}
      </div>
      <div>
        <div className="text-sm font-600 text-text-primary">{title}</div>
        <p className="mt-1 max-w-2xl text-sm leading-relaxed text-text-secondary">
          {message}
        </p>
      </div>
    </div>
  )
}

function AuditControls({
  search,
  onSearch,
  period,
  onPeriodChange,
  filters,
  onFilterChange,
}: {
  search: string
  onSearch: (value: string) => void
  period: string
  onPeriodChange: (value: string) => void
  filters: AuditFilterValues
  onFilterChange: (key: keyof AuditFilterValues, value: string) => void
}) {
  const periodLabel =
    PERIOD_OPTIONS.find((option) => option.value === period)?.label ??
    "All dates"
  const moduleLabel = MODULE_OPTIONS.find(
    (option) => option.value === filters.module,
  )?.label
  const resultLabel = RESULT_OPTIONS.find(
    (option) => option.value === filters.result,
  )?.label
  const severityLabel = SEVERITY_OPTIONS.find(
    (option) => option.value === filters.severity,
  )?.label

  return (
    <div className="rounded-lg border border-border bg-white p-4">
      <FilterBar
        search={search}
        onSearch={onSearch}
        searchPlaceholder="Search user, email, entity ID, module, action, work order, asset, request, approval or record ID"
        filters={
          <div className="flex flex-wrap gap-2">
            <SelectFilter
              label="Date Range"
              options={PERIOD_OPTIONS}
              value={period}
              onChange={onPeriodChange}
            />
            <SelectFilter
              label="User"
              options={EMPTY_FILTER_OPTIONS}
              value=""
              onChange={() => undefined}
            />
            <SelectFilter
              label="Role"
              options={EMPTY_FILTER_OPTIONS}
              value=""
              onChange={() => undefined}
            />
            <SelectFilter
              label="Module"
              options={MODULE_OPTIONS}
              value={filters.module}
              onChange={(value) => onFilterChange("module", value)}
            />
            <SelectFilter
              label="Action"
              options={EMPTY_FILTER_OPTIONS}
              value=""
              onChange={() => undefined}
            />
            <SelectFilter
              label="Entity Type"
              options={EMPTY_FILTER_OPTIONS}
              value=""
              onChange={() => undefined}
            />
            <SelectFilter
              label="Result"
              options={RESULT_OPTIONS}
              value={filters.result}
              onChange={(value) => onFilterChange("result", value)}
            />
            <SelectFilter
              label="Severity"
              options={SEVERITY_OPTIONS}
              value={filters.severity}
              onChange={(value) => onFilterChange("severity", value)}
            />
          </div>
        }
      />
      <div className="flex flex-wrap items-center gap-2 border-t border-border pt-3">
        <span className="inline-flex items-center gap-1.5 rounded bg-gold-50 px-2 py-1 text-xs font-500 text-gold-600">
          <CalendarDays size={13} />
          Date range: {periodLabel}
        </span>
        {moduleLabel && (
          <span className="inline-flex items-center rounded bg-surface-2 px-2 py-1 text-xs text-text-secondary">
            Module: {moduleLabel}
          </span>
        )}
        {resultLabel && (
          <span className="inline-flex items-center rounded bg-surface-2 px-2 py-1 text-xs text-text-secondary">
            Result: {resultLabel}
          </span>
        )}
        {severityLabel && (
          <span className="inline-flex items-center rounded bg-surface-2 px-2 py-1 text-xs text-text-secondary">
            Severity: {severityLabel}
          </span>
        )}
        <span className="inline-flex items-center gap-1.5 rounded bg-surface-2 px-2 py-1 text-xs text-text-secondary">
          <LockKeyhole size={13} />
          Immutable · Read only
        </span>
        <span className="inline-flex items-center gap-1.5 rounded bg-surface-2 px-2 py-1 text-xs text-text-secondary">
          <AlertTriangle size={13} />
          Audit service not connected
        </span>
      </div>
    </div>
  )
}

function AuditOverview() {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard
          title="Total Audit Events"
          value="—"
          subtitle="No audit data source connected"
          icon={<FileClock size={14} />}
          accent
        />
        <KpiCard
          title="Today's Events"
          value="—"
          subtitle="Current activity unavailable"
          icon={<CalendarDays size={14} />}
        />
        <KpiCard
          title="Workflow Changes"
          value="—"
          subtitle="Transition history unavailable"
          icon={<Workflow size={14} />}
        />
        <KpiCard
          title="Approval Actions"
          value="—"
          subtitle="Approval history unavailable"
          icon={<UserRoundCheck size={14} />}
        />
        <KpiCard
          title="Closure Approvals"
          value="—"
          subtitle="Closure records unavailable"
          icon={<ClipboardCheck size={14} />}
        />
        <KpiCard
          title="Critical Events"
          value="—"
          subtitle="Severity data unavailable"
          icon={<ShieldAlert size={14} />}
        />
        <KpiCard
          title="Failed Actions"
          value="—"
          subtitle="Result data unavailable"
          icon={<AlertTriangle size={14} />}
        />
        <KpiCard
          title="Evidence Records"
          value="—"
          subtitle="Evidence register unavailable"
          icon={<FileCheck2 size={14} />}
        />
      </div>

      <Section
        title="Audit Activity Overview"
        description="Activity by day, module, action, result and severity. Visualizations remain unavailable until verified audit data is connected."
      >
        <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">
          <AvailabilityPanel
            icon={<Activity size={18} />}
            title="Activity by day and module unavailable"
            message="No verified event series is available for a production chart."
          />
          <AvailabilityPanel
            icon={<SearchCheck size={18} />}
            title="Action, result and severity breakdown unavailable"
            message="No result or severity distribution is available for a production chart."
          />
        </div>
      </Section>

      <Section
        title="Recent Audit Events"
        description="Timestamp, actor, role, action, module, entity, entity ID, result, severity and details."
      >
        <DataTable
          columns={AUDIT_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No audit data source connected."
        />
      </Section>
    </div>
  )
}

function AuditLogs() {
  return (
    <div className="grid grid-cols-1 gap-5 xl:grid-cols-3">
      <div className="xl:col-span-2">
        <Section
          title="Primary Audit History"
          description="Searchable, filterable and immutable system history, including actor traceability and authentication-related activity."
        >
          <DataTable
            columns={AUDIT_COLUMNS}
            data={EMPTY_DATA}
            emptyMessage="No audit events found."
          />
        </Section>
      </div>
      <Section
        title="Event Detail"
        description="Selecting an event opens its read-only detail at the right on desktop and full width on smaller screens."
      >
        <AvailabilityPanel
          icon={<FileClock size={18} />}
          title="No event selected"
          message="Event ID, timestamp, actor, role, module, action, entity, result, severity, IP address, user agent, reason, description and evidence appear only when supplied by the audit service."
        />
      </Section>
    </div>
  )
}

function ClosureApprovals() {
  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center gap-2 rounded-lg border border-border bg-white p-4">
        <span className="text-xs font-600 uppercase tracking-wide text-text-secondary">
          Recorded states
        </span>
        <StatusBadge status="pending" />
        <StatusBadge status="approved" />
        <StatusBadge status="rejected" />
        <StatusBadge status="returned" />
      </div>
      <Section
        title="Closure Approval History"
        description="Read-only representation of closure decisions already completed in their source modules; this view does not introduce a new approval workflow."
      >
        <DataTable
          columns={CLOSURE_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No closure approval history available."
        />
      </Section>
    </div>
  )
}

function ChangeHistory() {
  return (
    <div className="space-y-6">
      <Section
        title="Field Change History"
        description="Field, previous value and updated value are displayed only when those details were recorded by the source system."
      >
        <DataTable
          columns={CHANGE_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No change history available."
        />
      </Section>
      <div className="grid grid-cols-1 gap-5 xl:grid-cols-2">
        <AvailabilityPanel
          icon={<History size={18} />}
          title="Change details are not available for this event."
          message="No before-and-after field values have been supplied by a connected audit source."
        />
        <AvailabilityPanel
          icon={<Workflow size={18} />}
          title="Workflow history unavailable"
          message="Request → review → approval → execution → completion → closure will appear as a read-only vertical timeline when verified transition data is available."
        />
      </div>
      <Section
        title="Workflow Transition History"
        description="Timestamp, actor, previous state, new state, reason and evidence."
      >
        <DataTable
          columns={WORKFLOW_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No workflow history available."
        />
      </Section>
    </div>
  )
}

function EvidenceAndExports() {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 gap-5 xl:grid-cols-2">
        <AvailabilityPanel
          icon={<FileCheck2 size={18} />}
          title="Evidence register unavailable"
          message="Evidence references appear only when supplied by existing source workflows."
        />
        <AvailabilityPanel
          icon={<FileArchive size={18} />}
          title="Audit exports unavailable"
          message="Generating, Ready, Failed and Expired states are supported visually, but no export or download is offered without a connected export service."
        />
      </div>
      <Section
        title="Evidence Register"
        description="Record, module, entity, evidence type, actor, timestamp and reference."
      >
        <DataTable
          columns={EVIDENCE_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No evidence records available."
        />
      </Section>
      <Section
        title="Audit Export History"
        description="Export ID, type, creator, date range, filters, created date, status, file and expiry."
      >
        <DataTable
          columns={EXPORT_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No audit exports available."
        />
      </Section>
    </div>
  )
}

function AuditReports() {
  return (
    <div className="space-y-6">
      <Section
        title="Report Library"
        description="Supported report concepts are visible for planning; View and Export remain unavailable until a report service supplies verified output."
      >
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">
          {REPORT_TYPES.map((reportType) => (
            <div
              key={reportType}
              className="rounded-lg border border-border bg-white p-4"
            >
              <div className="flex items-start gap-3">
                <div className="rounded bg-surface-2 p-2 text-text-secondary">
                  <FileBarChart size={16} />
                </div>
                <div>
                  <div className="text-sm font-600 text-text-primary">
                    {reportType}
                  </div>
                  <p className="mt-1 text-xs leading-relaxed text-text-secondary">
                    Report data source not connected.
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>
      <Section
        title="Report History"
        description="Generated report history and status appear here only when supplied by the report service."
      >
        <DataTable
          columns={REPORT_COLUMNS}
          data={EMPTY_DATA}
          emptyMessage="No audit reports available."
        />
      </Section>
    </div>
  )
}

export default function AuditPage({ currentPage = "audit" }: AuditPageProps) {
  const [search, setSearch] = useState("")
  const [period, setPeriod] = useState("30-days")
  const [filters, setFilters] = useState<AuditFilterValues>({
    module: "",
    result: "",
    severity: "",
  })
  const pageDetails = PAGE_DETAILS[currentPage] ?? PAGE_DETAILS.audit!

  return (
    <div className="min-h-full bg-surface">
      <PageHeader title={pageDetails.title} subtitle={pageDetails.subtitle} />

      <div className="space-y-6 p-6">
        <AuditControls
          search={search}
          onSearch={setSearch}
          period={period}
          onPeriodChange={setPeriod}
          filters={filters}
          onFilterChange={(key, value) =>
            setFilters((current) => ({ ...current, [key]: value }))
          }
        />

        {currentPage === "audit" && <AuditOverview />}
        {currentPage === "audit-logs" && <AuditLogs />}
        {currentPage === "audit-closures" && <ClosureApprovals />}
        {currentPage === "audit-history" && <ChangeHistory />}
        {currentPage === "audit-evidence" && <EvidenceAndExports />}
        {currentPage === "audit-reports" && <AuditReports />}

        <div className="flex flex-wrap items-center gap-x-5 gap-y-2 rounded-lg border border-border bg-white p-4 text-xs text-text-secondary">
          <span className="inline-flex items-center gap-1.5">
            <Shield size={13} className="text-gold-500" />
            Audit & Compliance is immutable and read only
          </span>
          <span className="inline-flex items-center gap-1.5">
            <CheckCircle2 size={13} />
            Source workflows and business records remain unchanged
          </span>
        </div>
      </div>
    </div>
  )
}
